name: deploy blog

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: biuld
        run: |
          npm install && npm run clear && npm run build && npm run deploy &&
          git add -f public/
          git commit -m 'add to gh-page'
          git subtree push --prefix public  origin gh-pages
